
export const LS_KEYS = {
    MAIN_TAB: 'kommuflow_mainTab',
    EXPANDED_RUN: 'kommuflow_expanded_run',
    PRICES_SEARCH_NAME: 'kommuflow_prices_searchName',
    PRICES_RARITIES: 'kommuflow_prices_rarities',
    PRICES_LEVEL_MIN: 'kommuflow_prices_levelMin',
    PRICES_LEVEL_MAX: 'kommuflow_prices_levelMax',
    PRICES_SORT_COLUMN: 'kommuflow_prices_sortColumn',
    PRICES_SORT_DIRECTION: 'kommuflow_prices_sortDirection',
    PRICES_PAGE: 'kommuflow_prices_page',
    PRICES_PER_PAGE: 'kommuflow_prices_perPage',
    PRICES_INSTANCES: 'kommuflow_prices_instances',
    RUNS_SUBTAB: 'kommuflow_runs_subTab',
    EXPANDED_HOUR_RUNS: 'kommuflow_expanded_hour_runs',
    TIME_PERIOD: 'kommuflow_time_period',
    SETTINGS_FOLDER_PATH: 'settings.folderPath',
    SETTINGS_DELETE_AFTER_OCR: 'settings.deleteAfterOCR',
    SETTINGS_LAUNCH_ON_STARTUP: 'settings.launchOnStartup',
    SETTINGS_MINIMIZE_TO_TRAY: 'settings.minimizeToTray',
    CONFIG_RUNS: 'kommuflow_configs',
    CONFIG_RUNS_EXPANDED: 'kommuflow_configs_expanded',
    CONFIG: 'kommuflow_config_v1',
    LANGUAGE: 'kommuflow_language',
    EXPANDED_INSTANCES: 'expandedInstances_v1',
    DETAILED_VIEW: 'kommuflow_detailed_view',
}